title: <p align="center"> Mohsin Tariq </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://in.linkedin.com/in/mohsin-tariq--reactjs">LinkedIn</a> |
  <a href="https://github.com/mohsin-tariq">GitHub</a>
  
  <br>   
  I'm working as a UI Expert using ReactJS, Redux and TypeScript.
  Handling multiple projects and working as an individual contributer as well.
  Total experience 12 years, experience in ReactJS 6 years.
  Currently persuing MS in AI and ML and adding different tech stack to my horizonal graph.
  <br>
  </p>

theme: jekyll-theme-minimal
